sudo: false
language: python
python:
- '3.5'
env:
  matrix:
  - TOXENV=py35-dj111
  - TOXENV=checkqa
install:
- pip install -U pip
- pip install tox codecov
script:
- tox
after_success:
- codecov
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
