sudo: false
language: python
python:
- '3.6'
env:
  matrix:
  - TOXENV=py36-dj20
  - TOXENV=qa
install:
- pip install -U pip
- pip install tox codecov
script:
- tox
after_success:
- cd src; codecov
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
